#docker-compose up -d
services:
  web:
    image: php:8.1.11-apache
    container_name: portfolio
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true